"use client";
import {Suspense,useEffect,useMemo,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";

type Page={title:string;slug:string;sections:{type:string;order:number;data:any}[]};
type Business={name?:string;category?:string;location?:string;description?:string;services?:string;phone?:string;whatsapp?:string;email?:string;hours?:string;social?:string;media?:string;reviews?:string;style?:string;headline?:string;slug?:string;primaryColor?:string;font?:string;logo?:string;heroImage?:string;seoTitle?:string;seoDescription?:string;showAbout?:boolean;showHours?:boolean;showContact?:boolean;showGallery?:boolean;showReviews?:boolean;showForm?:boolean;template?:string;pages?:Page[]};
const tabs=["Pages","Sections","Design","Text","Images","Services","Contact","SEO","Settings"];
const colors=["#183d2a","#174b63","#5b3a29","#4b356f","#7a3e3e","#1d3557"];const fonts=["Inter","Georgia","system-ui","Arial"];
const templates:Record<string,string>={restaurant:"Restaurant",automotive:"Automotive",beauty:"Beauty",fitness:"Fitness",construction:"Construction",professional:"Professional"};
const defaults:Page[]=[{title:"Home",slug:"home",sections:[{type:"hero",order:0,data:{enabled:true}},{type:"services",order:1,data:{enabled:true}},{type:"about",order:2,data:{enabled:true}},{type:"contact",order:3,data:{enabled:true}}]},{title:"About",slug:"about",sections:[{type:"about",order:0,data:{enabled:true}},{type:"contact",order:1,data:{enabled:true}}]},{title:"Contact",slug:"contact",sections:[{type:"contact",order:0,data:{enabled:true}},{type:"form",order:1,data:{enabled:true}}]}];

function EditorContent(){
 const router=useRouter();const params=useSearchParams();const requestedSlug=params.get("slug")||"";
 const [tab,setTab]=useState("Text");const [business,setBusiness]=useState<Business>({});const [websites,setWebsites]=useState<any[]>([]);const [pages,setPages]=useState<Page[]>(defaults);const [selectedPage,setSelectedPage]=useState("home");const [history,setHistory]=useState<Business[]>([]);const [future,setFuture]=useState<Business[]>([]);const [saved,setSaved]=useState(false);const [actionError,setActionError]=useState("");const [databaseBacked,setDatabaseBacked]=useState(false);const [device,setDevice]=useState("desktop");
 useEffect(()=>{let mounted=true;(async()=>{try{const response=await fetch("/api/businesses",{cache:"no-store"});if(response.ok){const data=await response.json();const all=data.businesses||[];const list=all.flatMap((b:any)=>((b.websites||[]).map((w:any)=>({business:b,website:w}))));setWebsites(list);const chosen=list.find((x:any)=>x.website.slug===requestedSlug)||list[0];if(mounted&&chosen){setDatabaseBacked(true);const b=chosen.business;const w=chosen.website;const config=w.config&&typeof w.config==="object"?w.config:{};setBusiness({...{showAbout:true,showHours:true,showContact:true,showGallery:true,showReviews:true,showForm:true},...b,...config,slug:w.slug,template:w.template});setPages(w.pages?.length?w.pages:defaults);setSelectedPage(w.pages?.[0]?.slug||"home");return;}}}catch{}setDatabaseBacked(false);try{const b=JSON.parse(localStorage.getItem("ll_business")||"{}");const p=JSON.parse(localStorage.getItem("ll_published")||"null");if(mounted)setBusiness({...{showAbout:true,showHours:true,showContact:true,showGallery:true,showReviews:true,showForm:true},...b,...p});}catch{}})();return()=>{mounted=false}},[requestedSlug]);
 const update=(k:keyof Business,v:string|boolean)=>setBusiness(b=>{setHistory(h=>[...h.slice(-19),b]);setFuture([]);return {...b,[k]:v}});
 const services=useMemo(()=>String(business.services||"").split(/[,\n]/).map(x=>x.trim()).filter(Boolean).map(x=>{const [name,...rest]=x.split("|");return{name:name.trim(),price:rest.join("|").trim()}}),[business.services]);
 const slug=useMemo(()=>business.slug||(business.name||"local-business").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"local-business",[business.slug,business.name]);
 const template=business.template||({Restaurant:"restaurant",Automotive:"automotive",Barber:"beauty",Beauty:"beauty",Fitness:"fitness",Construction:"construction","Professional services":"professional"}[String(business.category||"")])||"professional";
 const selected=pages.find(p=>p.slug===selectedPage)||pages[0];
 const persist=async(next:Business,status:"draft"|"published")=>{if(!databaseBacked){localStorage.setItem("ll_business",JSON.stringify(next));if(status==="published")localStorage.setItem("ll_published",JSON.stringify(next));return true;}try{const response=await fetch("/api/websites/"+encodeURIComponent(business.slug||slug),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,business:{...next,slug},config:next,pages})});if(!response.ok)return false;localStorage.setItem("ll_business",JSON.stringify(next));if(status==="published")localStorage.setItem("ll_published",JSON.stringify(next));return true;}catch{return false;}};
 const save=async()=>{const next={...business,slug,template};setActionError("");const ok=await persist(next,"draft");if(!ok){setSaved(false);setActionError("We couldn’t save your changes. Check your connection and try again.");return;}setSaved(true);setTimeout(()=>setSaved(false),1800);};
 const publish=async()=>{const next={...business,slug,template};setActionError("");const ok=await persist(next,"published");if(!ok){setSaved(false);setActionError("We couldn’t publish your website. Your changes were not published; please try again.");return;}setSaved(true);setTimeout(()=>{setSaved(false);router.push("/sites/"+slug)},700)};
 const addPage=()=>{let n=2;let pageSlug="page-2";while(pages.some(p=>p.slug===pageSlug)){n++;pageSlug=`page-${n}`;}const page={title:`Page ${n}`,slug:pageSlug,sections:[{type:"content",order:0,data:{enabled:true}}]};setPages(p=>[...p,page]);setSelectedPage(pageSlug);};
 const deletePage=()=>{if(!selected||pages.length<=1)return;const next=pages.filter(p=>p.slug!==selected.slug);setPages(next);setSelectedPage(next[0].slug);};
 const renamePage=(title:string)=>{if(!selected)return;setPages(p=>p.map(x=>x.slug===selected.slug?{...x,title}:x));};
 const addSection=()=>{if(!selected)return;setPages(p=>p.map(x=>x.slug===selected.slug?{...x,sections:[...x.sections,{type:"content",order:x.sections.length,data:{enabled:true}}]}:x));};
 const preview=()=>window.open("/sites/"+slug,"_blank");
 const upload=(key:"logo"|"heroImage",file:File)=>{const reader=new FileReader();reader.onload=()=>update(key,String(reader.result));reader.readAsDataURL(file)};
 const heroStyle=business.heroImage?{background:"linear-gradient(#0008,#0008),url("+business.heroImage+") center/cover"}:{background:business.primaryColor||"#183d2a"};
 return <div className="app"><header className="appbar"><a href="/dashboard">← Dashboard</a><b>Website Editor</b><div className="actions" style={{margin:0}}><select value={slug} onChange={e=>router.push("/editor?slug="+encodeURIComponent(e.target.value))} style={{maxWidth:180}}>{websites.map((x:any)=><option key={x.website.slug} value={x.website.slug}>{x.website.name}</option>)}</select><button className={"button secondary small "+(device==="desktop"?"selectedDevice":"")} onClick={()=>setDevice("desktop")}>Desktop</button><button className={"button secondary small "+(device==="tablet"?"selectedDevice":"")} onClick={()=>setDevice("tablet")}>Tablet</button><button className={"button secondary small "+(device==="mobile"?"selectedDevice":"")} onClick={()=>setDevice("mobile")}>Mobile</button><button className="button secondary small" disabled={!history.length} onClick={()=>{const prev=history[history.length-1];setHistory(h=>h.slice(0,-1));setFuture(f=>[business,...f]);setBusiness(prev)}}>Undo</button><button className="button secondary small" disabled={!future.length} onClick={()=>{const next=future[0];setFuture(f=>f.slice(1));setHistory(h=>[...h,business]);setBusiness(next)}}>Redo</button><button className="button secondary small" onClick={preview}>Preview</button><button className="button small" onClick={publish}>Publish Website</button></div></header>
 <div className="editor"><aside className="editorSide">{tabs.map(x=><button className={"sideLink "+(tab===x?"active":"")} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside>
 <section className="previewArea"><div className={"previewFrame "+(device==="mobile"?"mobilePreview":device==="tablet"?"tabletPreview":"")+" generatedSite layout"+(template.charAt(0).toUpperCase()+template.slice(1))} style={{fontFamily:business.font||"Inter",["--site-accent" as any]:business.primaryColor||"#183d2a"}}><div className="previewHero" style={heroStyle}>{business.logo&&<img src={business.logo} alt="" style={{maxWidth:110,maxHeight:60,objectFit:"contain",marginBottom:18}}/>}<small>{(business.name||"LOCAL BUSINESS").toUpperCase()} · {business.category||"Local business"}</small><h1>{business.headline||business.description?.split(".")[0]||"Professional service. Done right."}</h1><p>{business.location||"Your local area"}</p><div className="actions"><span className="pill">Contact us</span><span className="pill">Get directions</span></div></div><div className="previewContent"><p className="eyebrow">{selected?.title||"Home"} · {templates[template]||"Professional"}</p><h2>{template==="restaurant"?"Made for good meals.":template==="automotive"?"Practical service, clearly explained.":template==="fitness"?"Built around your goals.":template==="beauty"?"Look sharp. Feel confident.":template==="construction"?"Solid work from start to finish.":"Quality service, made simple."}</h2><div className="siteGrid">{services.length?services.map((x,i)=><div className="serviceBox" key={x.name+i}><b>{x.name}</b>{x.price&&<strong style={{display:"block",marginTop:8,color:business.primaryColor||"#183d2a"}}>{x.price}</strong>}<p className="muted">Professional service with clear communication.</p></div>):<div className="serviceBox">Add your services in the Services tab.</div>}</div>{business.showAbout!==false&&<div className="card" style={{marginTop:30}}><h3>About</h3><p className="muted">{business.description||"Tell customers what makes your business special."}</p></div>}<div className="grid3" style={{marginTop:30}}>{business.showHours!==false&&<div className="card"><h3>Hours</h3><p className="muted">{business.hours||"Add your opening hours."}</p></div>}{business.showContact!==false&&<div className="card"><h3>Contact</h3><p className="muted">{business.phone||business.email||"Add your contact details."}</p></div>}{business.showReviews!==false&&<div className="card"><h3>Reviews</h3><p className="muted">Reviews section enabled.</p></div>}</div></div></div></section>
 <aside className="inspector"><b>{tab}</b><p className="muted">Customize your website and save or publish when ready.</p>
 {tab==="Pages"?<><div className="actions"><button className="button small" onClick={addPage}>+ Add page</button><button className="button secondary small" onClick={deletePage} disabled={!selected||pages.length<=1}>Delete</button></div>{selected&&<><Field label="Page name" value={selected.title} onChange={renamePage}/><div className="choiceGrid">{pages.map(p=><button className={"choice "+(p.slug===selected.slug?"selected":"")} onClick={()=>setSelectedPage(p.slug)} key={p.slug}>{p.title}</button>)}</div><div className="card"><b>{selected.sections.length} sections</b><p className="muted">This page is stored in the database and can be expanded with section blocks.</p><button className="button secondary small" onClick={addSection}>+ Add section</button></div></>}</>:
 tab==="Sections"?<><p className="muted">Choose which content sections appear on the published site.</p><Toggle label="About section" checked={business.showAbout!==false} onChange={v=>update("showAbout",v)}/><Toggle label="Opening hours" checked={business.showHours!==false} onChange={v=>update("showHours",v)}/><Toggle label="Contact section" checked={business.showContact!==false} onChange={v=>update("showContact",v)}/><Toggle label="Gallery section" checked={business.showGallery!==false} onChange={v=>update("showGallery",v)}/><Toggle label="Reviews section" checked={business.showReviews!==false} onChange={v=>update("showReviews",v)}/><Toggle label="Enquiry form" checked={business.showForm!==false} onChange={v=>update("showForm",v)}/></>:
 tab==="Text"?<><Field label="Business name" value={business.name} onChange={v=>update("name",v)}/><Field label="Hero headline" value={business.headline||""} onChange={v=>update("headline",v)}/><Field label="About / description" value={business.description} onChange={v=>update("description",v)} area/></>:
 tab==="Design"?<><label>Accent color</label><div className="choiceGrid">{colors.map(c=><button className={"choice "+(business.primaryColor===c?"selected":"")} style={{borderColor:c}} onClick={()=>update("primaryColor",c)} key={c}>{c}</button>)}</div><div className="field"><label>Font</label><select value={business.font||"Inter"} onChange={e=>update("font",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></div><div className="field"><label>Website layout</label><select value={template} onChange={e=>update("template",e.target.value)}>{Object.entries(templates).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></div><div className="field"><label>Style</label><input value={business.style||""} onChange={e=>update("style",e.target.value)}/></div></>:
 tab==="Images"?<><Field label="Logo URL" value={business.logo} onChange={v=>update("logo",v)}/><FileUpload label="Upload logo" accept="image/*" onFile={f=>upload("logo",f)}/><Field label="Hero image URL" value={business.heroImage} onChange={v=>update("heroImage",v)}/><FileUpload label="Upload hero image" accept="image/*" onFile={f=>upload("heroImage",f)}/><Field label="Gallery / image URLs" value={business.media} onChange={v=>update("media",v)} area/></>:
 tab==="Services"?<><Field label="Services / products" value={business.services} onChange={v=>update("services",v)} area/><p className="muted">One per line or comma-separated. Optional price format: <b>Service | R250</b>.</p></>:
 tab==="Contact"?<><Field label="Phone" value={business.phone} onChange={v=>update("phone",v)}/><Field label="WhatsApp" value={business.whatsapp} onChange={v=>update("whatsapp",v)}/><Field label="Email" value={business.email} onChange={v=>update("email",v)}/><Field label="Location" value={business.location} onChange={v=>update("location",v)}/><Field label="Opening hours" value={business.hours} onChange={v=>update("hours",v)} area/><Field label="Social links" value={business.social} onChange={v=>update("social",v)} area/></>:
 tab==="SEO"?<><Field label="SEO title" value={business.seoTitle} onChange={v=>update("seoTitle",v)}/><Field label="SEO description" value={business.seoDescription} onChange={v=>update("seoDescription",v)} area/></>:
 tab==="Settings"?<><Field label="Website slug" value={slug} onChange={v=>update("slug",v)}/><div className="card"><b>Database publishing</b><p className="muted">Your website, pages and sections are persisted to your account database when connected.</p></div></>:<div className="card">Select a tab to edit your website.</div>}
 <button className="button" style={{marginTop:12,width:"100%",justifyContent:"center"}} onClick={save}>Save changes</button>{saved&&<p className="muted" role="status" style={{marginTop:10}}>Changes saved.</p>}{actionError&&<p className="authError" role="alert" style={{marginTop:10}}>{actionError}</p>}</aside></div></div>
}
export default function Editor(){return <Suspense fallback={<div className="app"><div className="card" style={{margin:24}}>Loading editor…</div></div>}><EditorContent/></Suspense>}
function Field({label,value,onChange,area=false}:{label:string;value?:string;onChange:(v:string)=>void;area?:boolean}){return <div className="field"><label>{label}</label>{area?<textarea rows={4} value={value||""} onChange={e=>onChange(e.target.value)}/>:<input value={value||""} onChange={e=>onChange(e.target.value)}/>}</div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="field" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,cursor:"pointer"}}><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} style={{width:18,height:18}}/></label>}
function FileUpload({label,accept,onFile}:{label:string;accept:string;onFile:(f:File)=>void}){return <div className="field"><label>{label}</label><input type="file" accept={accept} onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/></div>}