"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
type Business={name?:string;category?:string;location?:string;description?:string;services?:string;phone?:string;whatsapp?:string;email?:string;hours?:string;social?:string;media?:string;style?:string;headline?:string;slug?:string;primaryColor?:string;font?:string;logo?:string;heroImage?:string;seoTitle?:string;seoDescription?:string};
const tabs=["Pages","Sections","Design","Text","Images","Services","Contact","SEO","Settings"];
const colors=["#183d2a","#174b63","#5b3a29","#4b356f","#7a3e3e","#1d3557"];
const fonts=["Inter","Georgia","system-ui","Arial"];
export default function Editor(){
 const r=useRouter();const [tab,setTab]=useState("Text");const [business,setBusiness]=useState<Business>({});const [saved,setSaved]=useState(false);const [device,setDevice]=useState("desktop");
 useEffect(()=>{try{const b=JSON.parse(localStorage.getItem("ll_business")||"{}");const p=JSON.parse(localStorage.getItem("ll_published")||"null");setBusiness({...b,...p});}catch{}},[]);
 const update=(k:keyof Business,v:string)=>setBusiness(b=>({...b,[k]:v}));
 const services=useMemo(()=>String(business.services||"").split(",").map(x=>x.trim()).filter(Boolean),[business.services]);
 const slug=useMemo(()=>business.slug||(business.name||"local-business").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"local-business",[business.slug,business.name]);
 const save=()=>{const next={...business,slug};localStorage.setItem("ll_business",JSON.stringify(next));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const publish=()=>{const next={...business,slug};localStorage.setItem("ll_business",JSON.stringify(next));localStorage.setItem("ll_published",JSON.stringify(next));setSaved(true);setTimeout(()=>{setSaved(false);r.push("/sites/"+slug)},700)};
 const preview=()=>window.open("/sites/"+slug,"_blank");
 const heroStyle=business.heroImage?{background:"linear-gradient(#0008,#0008),url("+business.heroImage+") center/cover"}:{background:business.primaryColor||"#183d2a"};
 return <div className="app"><header className="appbar"><a href="/dashboard">← Dashboard</a><b>Website Editor</b><div className="actions" style={{margin:0}}><button className="button secondary small" onClick={()=>setDevice("desktop")}>Desktop</button><button className="button secondary small" onClick={()=>setDevice("mobile")}>Mobile</button><button className="button secondary small" onClick={preview}>Preview</button><button className="button small" onClick={publish}>{saved?"Saved ✓":"Publish Website"}</button></div></header>
 <div className="editor"><aside className="editorSide">{tabs.map(x=><button className={"sideLink "+(tab===x?"active":"")} onClick={()=>setTab(x)} key={x}>{x}</button>)}</aside>
 <section className="previewArea"><div className={"previewFrame "+(device==="mobile"?"mobilePreview":"")} style={{fontFamily:business.font||"Inter"}}><div className="previewHero" style={heroStyle}><small>{(business.name||"LOCAL BUSINESS").toUpperCase()} · {business.category||"Local business"}</small><h1>{business.headline||business.description?.split(".")[0]||"Professional service. Done right."}</h1><p>{business.location||"Your local area"}</p><div className="actions"><span className="pill">Contact us</span><span className="pill">Get directions</span></div></div><div className="previewContent"><p className="eyebrow">Services</p><h2>What we offer</h2><div className="siteGrid">{services.length?services.map(x=><div className="serviceBox" key={x}><b>{x}</b><p className="muted">Professional service with clear communication.</p></div>):<div className="serviceBox">Add your services in the Services tab.</div>}</div><div className="grid3" style={{marginTop:30}}><div className="card"><h3>About</h3><p className="muted">{business.description||"Tell customers what makes your business special."}</p></div><div className="card"><h3>Hours</h3><p className="muted">{business.hours||"Add your opening hours."}</p></div><div className="card"><h3>Contact</h3><p className="muted">{business.phone||business.email||"Add your contact details."}</p></div></div></div></div></section>
 <aside className="inspector"><b>{tab}</b><p className="muted">Customize your website and save or publish when ready.</p>
 {tab==="Text"||tab==="Pages"?<><Field label="Business name" value={business.name} onChange={v=>update("name",v)}/><Field label="Hero headline" value={business.headline||""} onChange={v=>update("headline",v)}/><Field label="About / description" value={business.description} onChange={v=>update("description",v)} area/></>:
 tab==="Design"?<><label>Accent color</label><div className="choiceGrid">{colors.map(c=><button className={"choice "+(business.primaryColor===c?"selected":"")} style={{borderColor:c}} onClick={()=>update("primaryColor",c)} key={c}>{c}</button>)}</div><div className="field"><label>Font</label><select value={business.font||"Inter"} onChange={e=>update("font",e.target.value)}>{fonts.map(f=><option key={f}>{f}</option>)}</select></div><div className="field"><label>Style</label><input value={business.style||""} onChange={e=>update("style",e.target.value)}/></div></>:
 tab==="Images"?<><Field label="Logo URL" value={business.logo} onChange={v=>update("logo",v)}/><Field label="Hero image URL" value={business.heroImage} onChange={v=>update("heroImage",v)}/><Field label="Gallery / image URLs" value={business.media} onChange={v=>update("media",v)} area/></>:
 tab==="Services"?<Field label="Services, separated by commas" value={business.services} onChange={v=>update("services",v)} area/>:
 tab==="Contact"?<><Field label="Phone" value={business.phone} onChange={v=>update("phone",v)}/><Field label="WhatsApp" value={business.whatsapp} onChange={v=>update("whatsapp",v)}/><Field label="Email" value={business.email} onChange={v=>update("email",v)}/><Field label="Social links" value={business.social} onChange={v=>update("social",v)} area/></>:
 tab==="SEO"?<><Field label="SEO title" value={business.seoTitle} onChange={v=>update("seoTitle",v)}/><Field label="SEO description" value={business.seoDescription} onChange={v=>update("seoDescription",v)} area/></>:
 tab==="Settings"?<><Field label="Website slug" value={slug} onChange={v=>update("slug",v)}/><div className="card"><b>Publishing</b><p className="muted">This demo currently uses browser storage. Real accounts, database persistence, payments and custom domains still require backend integrations.</p></div></>:
 <div className="card"><b>Sections</b><p className="muted">Your site includes hero, services, about, hours and contact sections.</p></div>}
 <button className="button" style={{marginTop:12,width:"100%",justifyContent:"center"}} onClick={save}>Save changes</button></aside></div></div>
}
function Field({label,value,onChange,area=false}:{label:string;value?:string;onChange:(v:string)=>void;area?:boolean}){return <div className="field"><label>{label}</label>{area?<textarea rows={4} value={value||""} onChange={e=>onChange(e.target.value)}/>:<input value={value||""} onChange={e=>onChange(e.target.value)}/>}</div>}