export const examples=[
 {slug:"northside-auto-works",type:"Automotive",category:"Automotive",name:"Northside Auto Works",tag:"Honest repairs. Done right.",headline:"Reliable automotive care without the runaround.",description:"Diagnostics, servicing and repairs for everyday drivers. Clear communication, practical advice and quality workmanship.",location:"Cape Town, Western Cape",services:["Diagnostics","Brake service","Engine repairs","Oil & filter service"],hours:"Mon–Fri 08:00–17:30 · Sat 08:00–13:00",style:"Professional",primaryColor:"#183d2a"},
 {slug:"harbour-table",type:"Restaurant",category:"Restaurant",name:"Harbour Table",tag:"Local food, coastal soul.",headline:"Fresh coastal plates made for long lunches.",description:"A relaxed neighbourhood restaurant serving seasonal food, fresh seafood and generous breakfasts near the coast.",location:"Saldanha Bay, Western Cape",services:["Breakfast","Seafood lunch","Dinner","Private dining"],hours:"Tue–Sun 08:00–22:00",style:"Friendly",primaryColor:"#174b63"},
 {slug:"oak-and-iron",type:"Barber",category:"Beauty",name:"Oak & Iron Barbers",tag:"Classic cuts. Modern finish.",headline:"Sharp cuts, clean fades and a proper barbershop experience.",description:"Traditional barbering with a modern finish. Walk-ins welcome when available, appointments recommended.",location:"Stellenbosch, Western Cape",services:["Classic cut","Skin fade","Beard trim","Hot towel"],hours:"Mon–Sat 09:00–18:00",style:"Bold",primaryColor:"#5b3a29"},
 {slug:"summit-fitness",type:"Fitness",category:"Fitness",name:"Summit Fitness Studio",tag:"Train stronger. Live better.",headline:"Coaching that fits real people and real schedules.",description:"Strength coaching, small-group sessions and personal training in a focused, welcoming studio.",location:"Durbanville, Western Cape",services:["Strength coaching","Small groups","Personal training","Mobility"],hours:"Mon–Fri 05:30–20:00 · Sat 07:00–12:00",style:"Modern",primaryColor:"#4b356f"},
 {slug:"buildright-projects",type:"Construction",category:"Construction",name:"BuildRight Projects",tag:"Built properly. Built to last.",headline:"Reliable building and renovation work from start to finish.",description:"Residential construction, renovations and maintenance with practical project management and clear communication.",location:"Paarl, Western Cape",services:["Renovations","New builds","Painting","Maintenance"],hours:"Mon–Fri 07:00–17:00",style:"Professional",primaryColor:"#1d3557"},
 {slug:"coastline-electrical",type:"Professional services",category:"Electrician",name:"Coastline Electrical",tag:"Safe power. Professional service.",headline:"Electrical work you can trust.",description:"Domestic electrical installations, fault finding, lighting and maintenance for homes and small businesses.",location:"Vredenburg, Western Cape",services:["Fault finding","Lighting","Installations","Maintenance"],hours:"Mon–Fri 07:30–17:00 · Emergency call-outs available",style:"Professional",primaryColor:"#7a3e3e"},
 {slug:"cleanline-home-care",type:"Local service",category:"Cleaning",name:"CleanLine Home Care",tag:"A cleaner home, without the hassle.",headline:"Reliable home cleaning for busy households.",description:"Regular and once-off home cleaning with flexible scheduling and straightforward service.",location:"Hopefield, Western Cape",services:["Home cleaning","Deep cleaning","Move-out cleaning","Office cleaning"],hours:"Mon–Fri 08:00–17:00",style:"Friendly",primaryColor:"#174b63"}
];
export const features=["AI website generation","Mobile-first layouts","Custom domains","WhatsApp buttons","Google Maps","Business hours","Services & products","Galleries","Reviews","Contact forms","Local SEO","Analytics"];