"use client";
import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {examples} from "@/lib/demo";
export default function Site(){
 const params=useParams<{slug:string}>();const slug=params.slug;const [site,setSite]=useState<any>(null);
 useEffect(()=>{let published=null;try{published=JSON.parse(localStorage.getItem("ll_published")||"null")}catch{}const demo=examples.find(x=>x.slug===slug);setSite(published?.slug===slug?published:demo||null)},[slug]);
 if(!site)return <main className="authPage"><p className="muted">Loading website...</p></main>;
 const services=Array.isArray(site.services)?site.services:String(site.services||"").split(",").map((x:string)=>x.trim()).filter(Boolean);
 const hero=site.heroImage?{background:"linear-gradient(#0008,#0008),url("+site.heroImage+") center/cover"}:{background:site.primaryColor||"#183d2a"};
 return <main style={{background:"#fff",minHeight:"100vh",fontFamily:site.font||"Inter"}}><div className="previewHero" style={hero}><div style={{maxWidth:1000,margin:"auto"}}>{site.logo&&<img src={site.logo} alt="" style={{maxWidth:110,maxHeight:60,objectFit:"contain",marginBottom:20}}/>}<small>{site.name.toUpperCase()} · {site.category||site.type||"Local business"}</small><h1>{site.headline||site.tag||site.description?.split(".")[0]||"Welcome to our business."}</h1><p>{site.location}</p><div className="actions"><a className="pill" href={site.whatsapp?"https://wa.me/"+String(site.whatsapp).replace(/\D/g,""):"#"}>WhatsApp</a>{site.phone&&<a className="pill" href={"tel:"+site.phone}>Call us</a>}{site.location&&<a className="pill" href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(site.location)} target="_blank" rel="noreferrer">Get directions</a>}</div></div></div><section className="section"><div className="sectionHead"><span className="eyebrow">Services</span><h2>What we offer</h2></div><div className="grid">{services.map((s:string)=><div className="card" key={s}><h3>{s}</h3><p className="muted">Professional service with clear communication.</p></div>)}</div><div className="grid3" style={{marginTop:40}}><div className="card"><h3>About</h3><p className="muted">{site.description||"A local business focused on quality service and a great customer experience."}</p></div><div className="card"><h3>Hours</h3><p className="muted">{site.hours||"Contact us for opening hours."}</p></div><div className="card"><h3>Contact</h3><p className="muted">{site.phone||site.email||site.location||"Get in touch with us."}</p></div></div>{site.media&&<div style={{marginTop:40}}><span className="eyebrow">Gallery</span><div className="grid3" style={{marginTop:18}}>{String(site.media).split(/[,\n]/).map((url:string)=><img key={url} src={url.trim()} alt="" style={{width:"100%",height:220,objectFit:"cover",borderRadius:14}}/>)}</div></div>}</section><footer className="footer"><span><b>{site.name}</b> · {site.location||"Local business"}</span><span>{site.phone||site.email||"Get in touch"} · Built with LocalLaunch</span></footer></main>;
}